### ISSUE TITLE
I reference dependencies' release versions only

### ISSUE THREAD

**Issue by sebwarnke** [camunda-consulting/showroom-customer-onboarding#7]
https://github.com/camunda-consulting/camunda-showcase-insurance-application/blob/16fb6016bd4407de6b267b58bfb1c31ba29d14c2/pom.xml#L77-L81

`pom.xml` should not contain SNAPSHOT builds that are available locally only.

**Comment by anhaltFelix** [comment]
fixed by https://github.com/camunda-consulting/showroom-customer-onboarding/commit/337845f8160cee21aa0c075ecefbfa39cb008763
